# load 3d nifti data of the mask saved in the package
dim(mask)

readline("press any key to continue")
# simulate fMRI data within dimension of 64*64*40 and our saved mask
# specify the starting time points of each simulated period and the duration of it
fmri_generate = fmri_simulate_func(dim_data = c(64, 64, 40), mask = mask, 
								   ons = c(1, 21, 41, 61, 81, 101, 121, 141), 
								   dur = c(10, 10, 10, 10, 10, 10, 10, 10))
								 
readline("press any key to continue")
# For simplicity here we use t-test to generate p-values. We also have other tests available. See more details in fmri_stimulus_detect.
# apply our p value detection function on our simulated fMRI data, choosing t test
p_simulate_ttest_raw = 
fmri_stimulus_detect(fmridata= fmri_generate$fmri_data, 
					 mask = fmri_generate$mask,
					 stimulus_idx = fmri_generate$on_time,
					 method = "t-test" , 
					 ons = fmri_generate$ons, 
					 dur = fmri_generate$dur)
			
readline("press any key to continue")
# make the 2d plot of our simulated data based on the p value generated above from sagittal, coronal and axial view
for(axis in c("x", "y", "z")){
  axis_i = switch(axis, 
                  "x" = {35},
                  "y" = {30},
                  "z" = {22})
  print(fmri_2dvisual(p_simulate_ttest_raw, list(axis, axis_i), 
                      hemody_data=NULL, mask_3d=fmri_generate$mask, 
                      p_threshold = 0.05, legend_show = TRUE, 
                      method = "scale_p",
                      color_pal = "YlOrRd", multi_pranges=TRUE))
}
			
readline("press any key to continue")
# make the 3d plot of our simulated data based on the p value generated above, using scale_p method
fmri_3dplot_df = fmri_3dvisual(p_simulate_ttest_raw, fmri_generate$mask, 
							   p_threshold = 0.05, method="scale_p", multi_pranges=TRUE)

print(fmri_3dplot_df$plot)


readline("press any key to continue")
# load 3d nifti data of p value
dim(pval)


readline("press any key to continue")
# post-hoc test
# do the fdr correction
pval_fdr = fmri_post_hoc(pval , fdr_corr = "fdr",
						 spatial_cluster.thr = NULL,
						 spatial_cluster.size = NULL, 
						 show_comparison = FALSE)
# do the spatial clustering
pval_posthoc = fmri_post_hoc(pval_fdr, fdr_corr = NULL,
							 spatial_cluster.thr = 0.05,
							 spatial_cluster.size = 5, 
							 show_comparison = FALSE)

readline("press any key to continue")
# to verify the mask of the simulated data is the same as the saved p value's corresponding mask
if(all(fmri_generate$mask==mask[,,]) == TRUE){
# make comparison of the 3d plot of two set of p values. One is generated by our simulated data, 
# the other is the one saved in our package
print( fmri_pval_comparison_3d(list(p_simulate_ttest_raw, pval_posthoc), mask, 
				          	   list(0.05, 0.05), list("scale_p", "scale_p"), 
				          	   multi_pranges=FALSE) )

fmri_pval_comparison_2d(list(p_simulate_ttest_raw, pval_posthoc), 
						list('pval_simulated', 'pval_posthoc'),
						list(list(35, 33, 22), list(40, 26, 33)), 
						hemody_data = NULL, 
						mask_3d = mask, p_threshold = 0.05, 
						legend_show = FALSE, method = 'scale_p',
						color_pal = "YlOrRd", multi_pranges=FALSE)
}

