#' @title mixedDistFunc
#' @description This function generates a new distribution that is mixed model of two normal distributions
#' @details This function takes in two pairs of mean and standard deviation to be used in two gaussian
#' distributions. In addition, a weight parameter is also needed to adjust the proportion of both gaussian.
#' @param n A integer, specifies number of random numbers generated by each normal distribution
#' @param weight Weight of the first normal distribution
#' @param mu1 Mean of the first normal distribution
#' @param mu2 Mean of the secondnormal distribution
#' @param sig1 Standard deviation of the first normal distribution
#' @param sig2 Standard deviation of the second normal distribution
#' @return A number or numbers that is a combination of two normal distributions
#' @examples
#' n=10000;mu1 <- 0; mu2 <- 5;sig1 <- 1; sig2 <- 3;weight <- 0.7
#' xA <- mixedDistFunc(n=n, weight, mu1, mu2, sig1, sig2)
#' hist(xA, freq = F)
#' @author SOCR team <http://socr.umich.edu/people/>
#' @export
mixedDistFunc <- function (n, weight, mu1, mu2, sig1, sig2) {
  set.seed(1234); U <- rnorm(n, mean=mu1, sd = sig1)
  set.seed(1234); V <- rnorm(n,mean=mu2, sd = sig2)
  # randomly choose U or V
  set.seed(1234); wght <- rbinom(n, size=1, prob=weight)
  X <- U*(1 - wght) + V*wght
}
