#' @title phase3_pval
#'
#' @description a 64*64*40 3D array containing a sample p values for the third phase of three-phase ROI analysis, generated by the post-hoc process for phase2_pval
#'
#' @docType data
#' @keywords array
#' @name phase3_pval
#' @usage phase3_pval
#' @format a 3D array containing p values
#'
NULL
