#' @title pval1
#'
#' @description a 64*64*40 3D array containing p values, generated by the real fMRI data with the hemodynamic response function method
#'
#' @docType data
#' @keywords array
#' @name pval1
#' @usage pval1
#' @format a 3D array containing p values
#'
NULL
