#' @title pval2
#'
#' @description a 64*64*40 3D array containing p values, generated by the simulated fMRI data with the t-test method
#'
#' @docType data
#' @keywords array
#' @name pval2
#' @usage pval2
#' @format a 3D array containing p values
#'
NULL
