#' @title modArima_train
#'
#' @description fitted ARIMA(X) model result. Generated by function \code{auto.arima()}
#'
#' @docType data
#' @keywords ARIMA(X) model result
#' @name modArima_train
#' @usage modArima_train
#' @format a list result generated by function \code{auto.arima()}
#'
NULL