#' @title xA_fMRI_1D_x20_y20_z11
#'
#' @description a vector generated from a 4 dimensions dataset. The original dataset is a 4D dataset containing
#' a 3 dimensions space and a time dimension. this vector is generated by fixing space dimensions to get different
#' value of different time. Fixed (x,y,z) is (20,20,11).
#'
#' @docType data
#' @keywords vector
#' @name xA_fMRI_1D_x20_y20_z11
#' @usage xA_fMRI_1D_x20_y20_z11
#' @format a vector contains a time series information
#'
NULL